/***
 * //////////////////////////////////////////////////////////////
 * TYPES (タイプ)
 * ----------------------
 *
 * タイプは、アクション、リデューサ、saga(または他の)ミドルウェアで使用するための定数です。
 * Typeはアクションの中で、ミドルウェアやリデューサーに命令を伝えるために使われます。
 * 全てのアクションタイプは、グループ化しやすいように以下の配列に格納され、選択されます。
 * //////////////////////////////////////////////////////////////
 */

// 注文エベント
const FRONT_SHOPPING_ORDER = "FRONT_SHOPPING_ORDER";
const FRONT_SHOPPING_ORDER_LOADING = "FRONT_SHOPPING_ORDER_LOADING";
const FRONT_SHOPPING_ORDER_SUCCESS = "FRONT_SHOPPING_ORDER_SUCCESS";
const FRONT_SHOPPING_ORDER_FAILURE = "FRONT_SHOPPING_ORDER_FAILURE";

// 支払い方法
const FRONT_SHOPPING_PAYMENT_METHOD = "FRONT_SHOPPING_PAYMENT_METHOD";
const FRONT_SHOPPING_PAYMENT_METHOD_LOADING = "FRONT_SHOPPING_PAYMENT_METHOD_LOADING";
const FRONT_SHOPPING_PAYMENT_METHOD_SUCCESS = "FRONT_SHOPPING_PAYMENT_METHOD_SUCCESS";
const FRONT_SHOPPING_PAYMENT_METHOD_FAILURE = "FRONT_SHOPPING_PAYMENT_METHOD_FAILURE";

// 注文を確定する
const FRONT_SHOPPING_ORDER_CONFIRM_REQUEST = "FRONT_SHOPPING_ORDER_CONFIRM_REQUEST";
const FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_LOADING = "FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_LOADING";
const FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_SUCCESS = "FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_SUCCESS";
const FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_FAILURE = "FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_FAILURE";

const types = {
    // 注文
    FRONT_SHOPPING_ORDER,
    FRONT_SHOPPING_ORDER_LOADING,
    FRONT_SHOPPING_ORDER_SUCCESS,
    FRONT_SHOPPING_ORDER_FAILURE,

    // 支払い方法
    FRONT_SHOPPING_PAYMENT_METHOD,
    FRONT_SHOPPING_PAYMENT_METHOD_LOADING,
    FRONT_SHOPPING_PAYMENT_METHOD_SUCCESS,
    FRONT_SHOPPING_PAYMENT_METHOD_FAILURE,

    // 注文を確定する
    FRONT_SHOPPING_ORDER_CONFIRM_REQUEST,
    FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_LOADING,
    FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_SUCCESS,
    FRONT_SHOPPING_ORDER_CONFIRM_REQUEST_FAILURE
}

export default types;
